//*****************************************************************************
//
//! @file am_devices_adau1777.c
//!
//! @brief Analog Devices ADAU1777 Digital Audio Amplifier Driver with I2C Interface.
//!
//! @addtogroup devices_adau1777 ADAU1777 I2C Audio Amplifier Driver
//! @ingroup devices
//! @{
//!
//! Purpose: This module provides a comprehensive hardware abstraction layer
//!          for the Analog Devices ADAU1777 digital audio amplifier. The driver
//!          enables high-performance audio playback with extensive configuration
//!          options through I2C control interface. It supports wide sample rate
//!          ranges, multiple audio interface modes, and gain
//!          control. Configuration tables are generated using Analog Devices'
//!          SigmaStudio tool for optimal audio performance and system integration.
//!
//! @section devices_adau1777_features Key Features
//!
//! 1. @b High-Performance @b Audio @b Amplification: Digital Class-D amplifier with superior audio quality.
//! 2. @b Wide @b Sample @b Rate @b Support: 8kHz to 192kHz sample rates for diverse audio applications.
//! 3. @b Flexible @b Audio @b Interfaces: Stereo modes.
//! 4. @b BclkRate @b Configuration: 16bclks/channel, 32bclks/channel support.
//! 5. @b Programmable @b Gain @b Control: Software-controlled volume adjustment.
//! 6. @b SigmaStudio @b Integration: Uses configuration tables generated by SigmaStudio tool.
//! 7. @b I2C @b Interface: Standard I2C communication for control and configuration.
//!
//! @section devices_adau1777_functionality Functionality
//!
//! - Initialize and configure ADAU1777 amplifier via I2C interface
//! - Configure wide range of audio sample rates (8kHz to 192kHz)
//! - Set audio interface mode (Stereo I2S)
//! - Configure I2S frame width(16bclks/channel, 32bclks/channel)
//! - Control amplifier gain for volume adjustment
//! - Load SigmaStudio-generated configuration tables
//! - Handle register-level configuration with read/write operations
//! - Support full reset and initialization sequences
//!
//! @section devices_adau1777_usage Usage
//!
//! 1. Initialize I2C interface with am_devices_adau1777_i2c_init()
//! 2. Initialize ADAU1777 device with am_devices_adau1777_init()
//! 3. Configure sample rate with am_devices_adau1777_set_sample_rate()
//! 4. Set audio interface mode with am_devices_adau1777_set_sai_ms()
//! 5. Configure i2s parameters with am_devices_adau1777_set_bclk_rate()
//! 6. Adjust dac volume with am_devices_adau1777_set_dac_0_volume(), am_devices_adau1777_set_dac_1_volume()
//! 7. Mute dac with am_devices_adau1777_mute_dac_0(), am_devices_adau1777_mute_dac_1()
//! 8. Play audio through configured amplifier
//! 9. Deinitialize device with am_devices_adau1777_deinit()
//! 10. Deinitialize I2C interface with am_devices_adau1777_i2c_deinit()
//!
//! @section devices_adau1777_configuration Configuration
//!
//! - Set up I2C interface parameters and timing
//! - Configure audio sample rates based on system requirements
//! - Set up audio interface mode (Stereo) for system topology
//! - Load SigmaStudio-generated configuration tables
//! - Set up gain control ranges and behavior
//! - Optimize register settings for specific audio applications
//
//*****************************************************************************

//*****************************************************************************
//
// Copyright (c) 2026, Ambiq Micro, Inc.
// All rights reserved.
//
// This is part of revision stable-2026.06.18 of the AmbiqSuite Development Package.
//
//*****************************************************************************
#include "am_devices_adau1777.h"
#include "am_bsp.h"
#include "string.h"
#include "am_util_delay.h"
#include "am_util_debug.h"
#include "am_util_stdio.h"
#include <math.h>

//*****************************************************************************
//
// Macro definitions.
//
//*****************************************************************************

/*
    Default registers configuration table. Generated by SigmaStudio tool.
    Generation step:
    * Create a ADAU1777 project
    * Modify project parameters
        * Control/Status: Software Master
        * Datapath
            * Sample Rate: 16KHz
            * I2S Mode: Stereo
            * Bclk Rate: 32 bits/Channel
            * DAC0: Volume: 0dB
            * DAC1: Volume: 0dB
            * DAC0: Mute Control: DAC0 Unmuted
            * DAC1: Mute Control: DAC1 Unmuted
            * I2S Mode: Slave
    * Export System File. This function will output .h file.
*/

/* DSP Program Data */
#define PROGRAM_SIZE_IC_1 64
#define PROGRAM_ADDR_IC_1 128
ADI_REG_TYPE Program_Data_IC_1[PROGRAM_SIZE_IC_1] = {
0x00, 0x82,
0x01, 0x80,
0x00, 0x83,
0x01, 0x81,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
0x00, 0x00,
};

/* DSP Parameter (Coefficient) Data */
#define BANK_A_PARAMETERS_SIZE_IC_1 640
#define BANK_A_PARAMETERS_ADDR_IC_1 224
ADI_REG_TYPE BANK_A_PARAMETERS_IC_1[BANK_A_PARAMETERS_SIZE_IC_1] = {
0x08, 0x00, 0x00, 0x00,
0x08, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00,
};


/* Register Default - IC 1.DAC0_VOLUME */
ADI_REG_TYPE R0_DAC0_VOLUME_IC_1_Default[REG_DAC0_VOLUME_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.DAC1_VOLUME */
ADI_REG_TYPE R1_DAC1_VOLUME_IC_1_Default[REG_DAC1_VOLUME_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.OP_STAGE_MUTES */
ADI_REG_TYPE R2_OP_STAGE_MUTES_IC_1_Default[REG_OP_STAGE_MUTES_IC_1_BYTE] = {
0x0F
};

/* Register Default - IC 1.PLL_CTRL0 Register */
ADI_REG_TYPE R3_PLL_CTRL0_IC_1_Default[REG_PLL_CTRL0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PLL_CTRL1 Register */
ADI_REG_TYPE R4_PLL_CTRL1_IC_1_Default[REG_PLL_CTRL1_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PLL_CTRL2 Register */
ADI_REG_TYPE R5_PLL_CTRL2_IC_1_Default[REG_PLL_CTRL2_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PLL_CTRL3 Register */
ADI_REG_TYPE R6_PLL_CTRL3_IC_1_Default[REG_PLL_CTRL3_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PLL_CTRL4 Register */
ADI_REG_TYPE R7_PLL_CTRL4_IC_1_Default[REG_PLL_CTRL4_IC_1_BYTE] = {
0x20
};

/* Register Default - IC 1.PLL_CTRL5 Register */
// ADI_REG_TYPE R8_PLL_CTRL5_IC_1_Default[REG_PLL_CTRL5_IC_1_BYTE] = {
// 0x01
// };

/* Register Default - IC 1.CLK_CONTROL Register */
ADI_REG_TYPE R9_CLK_CONTROL_IC_1_Default[REG_CLK_CONTROL_IC_1_BYTE] = {
0x01
};

/* Register Default - IC 1.Delay */
#define R10_DELAY_IC_1_ADDR 0x0
#define R10_DELAY_IC_1_SIZE 2
ADI_REG_TYPE R10_DELAY_IC_1_Default[R10_DELAY_IC_1_SIZE] = {
0x00, 0x05
};

/* Register Default - IC 1.CLKOUT_SEL Register */
ADI_REG_TYPE R11_CLKOUT_SEL_IC_1_Default[REG_CLKOUT_SEL_IC_1_BYTE] = {
0x07
};

/* Register Default - IC 1.REGULATOR Register */
ADI_REG_TYPE R12_REGULATOR_IC_1_Default[REG_REGULATOR_IC_1_BYTE] = {
0x01
};

/* Register Default - IC 1.CORE_CONTROL Register */
ADI_REG_TYPE R13_CORE_CONTROL_IC_1_Default[REG_CORE_CONTROL_IC_1_BYTE] = {
0x05
};

/* Register Default - IC 1.SLEEP_INST Register */
ADI_REG_TYPE R14_SLEEP_INST_IC_1_Default[REG_SLEEP_INST_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.CORE_ENABLE Register */
ADI_REG_TYPE R15_CORE_ENABLE_IC_1_Default[REG_CORE_ENABLE_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.ABSREG0 Register */
// ADI_REG_TYPE R16_DBREG0_IC_1_Default[REG_DBREG0_IC_1_BYTE] = {
// 0x00
// };

/* Register Default - IC 1.ABSREG1 Register */
// ADI_REG_TYPE R17_DBREG1_IC_1_Default[REG_DBREG1_IC_1_BYTE] = {
// 0x00
// };

/* Register Default - IC 1.ABSREG2 Register */
// ADI_REG_TYPE R18_DBREG2_IC_1_Default[REG_DBREG2_IC_1_BYTE] = {
// 0x00
// };

/* Register Default - IC 1.CORE_IN_MUX_0_1 Register */
ADI_REG_TYPE R19_CORE_IN_MUX_0_1_IC_1_Default[REG_CORE_IN_MUX_0_1_IC_1_BYTE] = {
0x10
};

/* Register Default - IC 1.CORE_IN_MUX_2_3 Register */
ADI_REG_TYPE R20_CORE_IN_MUX_2_3_IC_1_Default[REG_CORE_IN_MUX_2_3_IC_1_BYTE] = {
0xDC
};

/* Register Default - IC 1.DAC_SOURCE_0_1 Register */
ADI_REG_TYPE R21_DAC_SOURCE_0_1_IC_1_Default[REG_DAC_SOURCE_0_1_IC_1_BYTE] = {
0x10
};

/* Register Default - IC 1.PDM_SOURCE_0_1 Register */
ADI_REG_TYPE R22_PDM_SOURCE_0_1_IC_1_Default[REG_PDM_SOURCE_0_1_IC_1_BYTE] = {
0x32
};

/* Register Default - IC 1.SOUT_SOURCE_0_1 Register */
ADI_REG_TYPE R23_SOUT_SOURCE_0_1_IC_1_Default[REG_SOUT_SOURCE_0_1_IC_1_BYTE] = {
0x54
};

/* Register Default - IC 1.SOUT_SOURCE_2_3 Register */
ADI_REG_TYPE R24_SOUT_SOURCE_2_3_IC_1_Default[REG_SOUT_SOURCE_2_3_IC_1_BYTE] = {
0x66
};

/* Register Default - IC 1.SOUT_SOURCE_4_5 Register */
ADI_REG_TYPE R25_SOUT_SOURCE_4_5_IC_1_Default[REG_SOUT_SOURCE_4_5_IC_1_BYTE] = {
0x44
};

/* Register Default - IC 1.SOUT_SOURCE_6_7 Register */
ADI_REG_TYPE R26_SOUT_SOURCE_6_7_IC_1_Default[REG_SOUT_SOURCE_6_7_IC_1_BYTE] = {
0x76
};

/* Register Default - IC 1.ADC_SDATA_CH Register */
ADI_REG_TYPE R27_ADC_SDATA_CH_IC_1_Default[REG_ADC_SDATA_CH_IC_1_BYTE] = {
0x04
};

/* Register Default - IC 1.ASRCO_SOURCE_0_1 Register */
ADI_REG_TYPE R28_ASRCO_SOURCE_0_1_IC_1_Default[REG_ASRCO_SOURCE_0_1_IC_1_BYTE] = {
0x54
};

/* Register Default - IC 1.ASRCO_SOURCE_2_3 Register */
ADI_REG_TYPE R29_ASRCO_SOURCE_2_3_IC_1_Default[REG_ASRCO_SOURCE_2_3_IC_1_BYTE] = {
0x33
};

/* Register Default - IC 1.ASRC_MODE Register */
ADI_REG_TYPE R30_ASRC_MODE_IC_1_Default[REG_ASRC_MODE_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.ADC_CONTROL0 Register */
ADI_REG_TYPE R31_ADC_CONTROL0_IC_1_Default[REG_ADC_CONTROL0_IC_1_BYTE] = {
0x01
};

/* Register Default - IC 1.ADC_CONTROL1 Register */
ADI_REG_TYPE R32_ADC_CONTROL1_IC_1_Default[REG_ADC_CONTROL1_IC_1_BYTE] = {
0x01
};

/* Register Default - IC 1.ADC_CONTROL2 Register */
ADI_REG_TYPE R33_ADC_CONTROL2_IC_1_Default[REG_ADC_CONTROL2_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.ADC_CONTROL3 Register */
ADI_REG_TYPE R34_ADC_CONTROL3_IC_1_Default[REG_ADC_CONTROL3_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.ADC0_VOLUME Register */
ADI_REG_TYPE R35_ADC0_VOLUME_IC_1_Default[REG_ADC0_VOLUME_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.ADC1_VOLUME Register */
ADI_REG_TYPE R36_ADC1_VOLUME_IC_1_Default[REG_ADC1_VOLUME_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.ADC2_VOLUME Register */
ADI_REG_TYPE R37_ADC2_VOLUME_IC_1_Default[REG_ADC2_VOLUME_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.ADC3_VOLUME Register */
ADI_REG_TYPE R38_ADC3_VOLUME_IC_1_Default[REG_ADC3_VOLUME_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PGA_CONTROL_0 Register */
ADI_REG_TYPE R39_PGA_CONTROL_0_IC_1_Default[REG_PGA_CONTROL_0_IC_1_BYTE] = {
0x7F
};

/* Register Default - IC 1.PGA_CONTROL_1 Register */
ADI_REG_TYPE R40_PGA_CONTROL_1_IC_1_Default[REG_PGA_CONTROL_1_IC_1_BYTE] = {
0x7F
};

/* Register Default - IC 1.PGA_CONTROL_2 Register */
ADI_REG_TYPE R41_PGA_CONTROL_2_IC_1_Default[REG_PGA_CONTROL_2_IC_1_BYTE] = {
0x40
};

/* Register Default - IC 1.PGA_CONTROL_3 Register */
ADI_REG_TYPE R42_PGA_CONTROL_3_IC_1_Default[REG_PGA_CONTROL_3_IC_1_BYTE] = {
0x40
};

/* Register Default - IC 1.PGA_STEP_CONTROL Register */
ADI_REG_TYPE R43_PGA_STEP_CONTROL_IC_1_Default[REG_PGA_STEP_CONTROL_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PGA_10DB_BOOST Register */
ADI_REG_TYPE R44_PGA_10DB_BOOST_IC_1_Default[REG_PGA_10DB_BOOST_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.POP_SUPPRESS Register */
ADI_REG_TYPE R45_POP_SUPPRESS_IC_1_Default[REG_POP_SUPPRESS_IC_1_BYTE] = {
0x3F
};

/* Register Default - IC 1.TALKTHRU Register */
ADI_REG_TYPE R46_TALKTHRU_IC_1_Default[REG_TALKTHRU_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.TALKTHRU_GAIN0 Register */
ADI_REG_TYPE R47_TALKTHRU_GAIN0_IC_1_Default[REG_TALKTHRU_GAIN0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.TALKTHRU_GAIN1 Register */
ADI_REG_TYPE R48_TALKTHRU_GAIN1_IC_1_Default[REG_TALKTHRU_GAIN1_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MIC_BIAS Register */
ADI_REG_TYPE R49_MIC_BIAS_IC_1_Default[REG_MIC_BIAS_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.DAC_CONTROL1 Register */
ADI_REG_TYPE R50_DAC_CONTROL1_IC_1_Default[REG_DAC_CONTROL1_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.DAC0_VOLUME Register */
ADI_REG_TYPE R51_DAC0_VOLUME_IC_1_Default[REG_DAC0_VOLUME_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.DAC1_VOLUME Register */
ADI_REG_TYPE R52_DAC1_VOLUME_IC_1_Default[REG_DAC1_VOLUME_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.OP_STAGE_MUTES Register */
ADI_REG_TYPE R53_OP_STAGE_MUTES_IC_1_Default[REG_OP_STAGE_MUTES_IC_1_BYTE] = {
0x0F
};

/* Register Default - IC 1.SAI_0 Register */
ADI_REG_TYPE R54_SAI_0_IC_1_Default[REG_SAI_0_IC_1_BYTE] = {
0x03
};

/* Register Default - IC 1.SAI_1 Register */
ADI_REG_TYPE R55_SAI_1_IC_1_Default[REG_SAI_1_IC_1_BYTE] = {
0x40
};

/* Register Default - IC 1.SOUT_CONTROL0 Register */
ADI_REG_TYPE R56_SOUT_CONTROL0_IC_1_Default[REG_SOUT_CONTROL0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.SOUT_CONTROL1 Register */
ADI_REG_TYPE R57_SOUT_CONTROL1_IC_1_Default[REG_SOUT_CONTROL1_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PDM_OUT Register */
ADI_REG_TYPE R58_PDM_OUT_IC_1_Default[REG_PDM_OUT_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PDM_PATTERN Register */
ADI_REG_TYPE R59_PDM_PATTERN_IC_1_Default[REG_PDM_PATTERN_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP0 Register */
ADI_REG_TYPE R60_MODE_MP0_IC_1_Default[REG_MODE_MP0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP1 Register */
ADI_REG_TYPE R61_MODE_MP1_IC_1_Default[REG_MODE_MP1_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP2 Register */
ADI_REG_TYPE R62_MODE_MP2_IC_1_Default[REG_MODE_MP2_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP3 Register */
ADI_REG_TYPE R63_MODE_MP3_IC_1_Default[REG_MODE_MP3_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP4 Register */
ADI_REG_TYPE R64_MODE_MP4_IC_1_Default[REG_MODE_MP4_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP5 Register */
ADI_REG_TYPE R65_MODE_MP5_IC_1_Default[REG_MODE_MP5_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.MODE_MP6 Register */
ADI_REG_TYPE R66_MODE_MP6_IC_1_Default[REG_MODE_MP6_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PB_VOL_SET Register */
ADI_REG_TYPE R67_PB_VOL_SET_IC_1_Default[REG_PB_VOL_SET_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PB_VOL_CONV Register */
ADI_REG_TYPE R68_PB_VOL_CONV_IC_1_Default[REG_PB_VOL_CONV_IC_1_BYTE] = {
0x87
};

/* Register Default - IC 1.DEBOUNCE_MODE Register */
ADI_REG_TYPE R69_DEBOUNCE_MODE_IC_1_Default[REG_DEBOUNCE_MODE_IC_1_BYTE] = {
0x05
};

/* Register Default - IC 1.RESERVED Register */
ADI_REG_TYPE R70_RESERVED_IC_1_Default[REG_RESERVED_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.OP_STAGE_CTRL Register */
ADI_REG_TYPE R71_OP_STAGE_CTRL_IC_1_Default[REG_OP_STAGE_CTRL_IC_1_BYTE] = {
0x30
};

/* Register Default - IC 1.DECIM_PWR_MODES Register */
ADI_REG_TYPE R72_DECIM_PWR_MODES_IC_1_Default[REG_DECIM_PWR_MODES_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.INTERP_PWR_MODES Register */
ADI_REG_TYPE R73_INTERP_PWR_MODES_IC_1_Default[REG_INTERP_PWR_MODES_IC_1_BYTE] = {
0x0F
};

/* Register Default - IC 1.BIAS_CONTROL0 Register */
ADI_REG_TYPE R74_BIAS_CONTROL0_IC_1_Default[REG_BIAS_CONTROL0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.BIAS_CONTROL1 Register */
ADI_REG_TYPE R75_BIAS_CONTROL1_IC_1_Default[REG_BIAS_CONTROL1_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PAD_CONTROL0 Register */
ADI_REG_TYPE R76_PAD_CONTROL0_IC_1_Default[REG_PAD_CONTROL0_IC_1_BYTE] = {
0x7F
};

/* Register Default - IC 1.PAD_CONTROL1 Register */
ADI_REG_TYPE R77_PAD_CONTROL1_IC_1_Default[REG_PAD_CONTROL1_IC_1_BYTE] = {
0x1F
};

/* Register Default - IC 1.PAD_CONTROL2 Register */
ADI_REG_TYPE R78_PAD_CONTROL2_IC_1_Default[REG_PAD_CONTROL2_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PAD_CONTROL3 Register */
ADI_REG_TYPE R79_PAD_CONTROL3_IC_1_Default[REG_PAD_CONTROL3_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PAD_CONTROL4 Register */
ADI_REG_TYPE R80_PAD_CONTROL4_IC_1_Default[REG_PAD_CONTROL4_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PAD_CONTROL5 Register */
ADI_REG_TYPE R81_PAD_CONTROL5_IC_1_Default[REG_PAD_CONTROL5_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.FAST_RATE Register */
ADI_REG_TYPE R82_FAST_RATE_IC_1_Default[REG_FAST_RATE_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.DAC_CONTROL0 Register */
ADI_REG_TYPE R83_DAC_CONTROL0_IC_1_Default[REG_DAC_CONTROL0_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.VOL_BYPASS Register */
ADI_REG_TYPE R84_VOL_BYPASS_IC_1_Default[REG_VOL_BYPASS_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.OP_STAGE_MUTES */
ADI_REG_TYPE R87_OP_STAGE_MUTES_IC_1_Default[REG_OP_STAGE_MUTES_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.DAC0_VOLUME */
ADI_REG_TYPE R88_DAC0_VOLUME_IC_1_Default[REG_DAC0_VOLUME_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.DAC1_VOLUME */
ADI_REG_TYPE R89_DAC1_VOLUME_IC_1_Default[REG_DAC1_VOLUME_IC_1_BYTE] = {
0x00
};

ADI_REG_TYPE linear_gain[16][4] = {
    {0x08, 0x00, 0x00, 0x00},  // 0dB
    {0x08, 0xF9, 0xE4, 0x93},  // 1dB
    {0x0A, 0x12, 0x47, 0x45},  // 2dB
    {0x0B, 0x4C, 0xE0, 0xB9},  // 3dB
    {0x0C, 0xAD, 0xDC, 0x62},  // 4dB
    {0x0E, 0x39, 0xEA, 0x57},  // 5dB
    {0x0F, 0xF6, 0x4B, 0xEC},  // 6dB
    {0x11, 0xE8, 0xE6, 0x8E},  // 7dB
    {0x14, 0x18, 0x57, 0xB0},  // 8dB
    {0x16, 0x8C, 0x0C, 0x63},  // 9dB
    {0x19, 0x4C, 0x58, 0x68},  // 10dB
    {0x1C, 0x62, 0x94, 0x14},  // 11dB
    {0x1F, 0xD9, 0x3C, 0x47},  // 12dB
    {0x23, 0xBC, 0x14, 0x83},  // 13dB
    {0x28, 0x18, 0x50, 0x59},  // 14dB
    {0x2C, 0xFC, 0xBF, 0xF4}   // 15dB
};

//*****************************************************************************
//
// Static variables.
//
//*****************************************************************************
static void *g_adau1777_IOMHandle = NULL;

//*****************************************************************************
//
// Local functions public.
//
//*****************************************************************************
// As SIGMA_WRITE_REGISTER_BLOCK is exported by SigmaStudio tool, so reserve it.
static uint32_t SIGMA_WRITE_REGISTER_BLOCK(uint8_t dev_addr, uint16_t reg,
                                           uint16_t data_len, ADI_REG_TYPE *data)
{
    return am_devices_adau1777_i2c_write(dev_addr, reg, (uint32_t *)data, data_len);
}

uint32_t am_devices_adau1777_i2c_read(uint32_t dev_addr, uint16_t reg_addr,
                                     uint32_t *p_buf, uint32_t size)
{
    am_hal_iom_transfer_t Transaction;

    Transaction.ui8Priority        = 1;
    Transaction.ui32InstrLen       = 2;
    Transaction.ui64Instr          = reg_addr;
    Transaction.eDirection         = AM_HAL_IOM_RX;
    Transaction.ui32NumBytes       = size;
    Transaction.pui32RxBuffer      = p_buf;
    Transaction.bContinue          = false;
    Transaction.ui8RepeatCount     = 0;
    Transaction.ui32PauseCondition = 0;
    Transaction.ui32StatusSetClr   = 0;

    Transaction.uPeerInfo.ui32I2CDevAddr = dev_addr;
    if (am_hal_iom_blocking_transfer(g_adau1777_IOMHandle, &Transaction) !=
        AM_HAL_STATUS_SUCCESS)
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_OPERATION;
    }

    return AM_DEVICES_ADAU1777_STATUS_SUCCESS;
}

uint32_t am_devices_adau1777_i2c_write(uint32_t dev_addr, uint16_t reg_addr,
                                      uint32_t *p_buf, uint32_t size)
{
    am_hal_iom_transfer_t Transaction;

    Transaction.ui8Priority        = 1;
    Transaction.ui32InstrLen       = 2;
    Transaction.ui64Instr          = reg_addr;
    Transaction.eDirection         = AM_HAL_IOM_TX;
    Transaction.ui32NumBytes       = size;
    Transaction.pui32TxBuffer      = p_buf;
    Transaction.bContinue          = false;
    Transaction.ui8RepeatCount     = 0;
    Transaction.ui32PauseCondition = 0;
    Transaction.ui32StatusSetClr   = 0;

    Transaction.uPeerInfo.ui32I2CDevAddr = dev_addr;
    if (am_hal_iom_blocking_transfer(g_adau1777_IOMHandle, &Transaction) !=
        AM_HAL_STATUS_SUCCESS)
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_OPERATION;
    }

    return AM_DEVICES_ADAU1777_STATUS_SUCCESS;
}

// ****************************************************************************
//
//  Initialize IOM I2C
//
// ****************************************************************************
uint32_t am_devices_adau1777_i2c_init(uint32_t             ui32Module,
                                     am_hal_iom_config_t *psIOMSettings)
{
    if (ui32Module > AM_REG_IOM_NUM_MODULES)
    {
        return AM_DEVICES_ADAU1777_STATUS_OUT_OF_RANGE;
    }

    if (g_adau1777_IOMHandle != NULL)
    {
        return AM_DEVICES_ADAU1777_STATUS_IN_USE;
    }

    //
    // Configure the IOM pins.
    //
    am_bsp_iom_pins_enable(ui32Module, AM_HAL_IOM_I2C_MODE);

    //
    // Initialize the IOM instance.
    // Enable power to the IOM instance.
    // Configure the IOM for Serial operation during initialization.
    // Enable the IOM.
    // HAL Success return is 0
    //
    if (am_hal_iom_initialize(ui32Module, &g_adau1777_IOMHandle) ||
        am_hal_iom_power_ctrl(g_adau1777_IOMHandle, AM_HAL_SYSCTRL_WAKE,
                              false) ||
        am_hal_iom_configure(g_adau1777_IOMHandle, psIOMSettings) ||
        am_hal_iom_enable(g_adau1777_IOMHandle))
    {
        return AM_DEVICES_ADAU1777_STATUS_HW_ERR;
    }

    return AM_DEVICES_ADAU1777_STATUS_SUCCESS;
}

// ****************************************************************************
//
//  Initialize the adau1777 chip
//
// ****************************************************************************
uint32_t am_devices_adau1777_init(uint8_t chip_addr)
{
    uint32_t status = AM_DEVICES_ADAU1777_STATUS_SUCCESS;

    /* Register configuration generated by SigmaStudio tool */
    status = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC0_VOLUME_IC_1_ADDR,
                                REG_DAC0_VOLUME_IC_1_BYTE,
                                R0_DAC0_VOLUME_IC_1_Default);
    if (status != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return status;
    }

    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC1_VOLUME_IC_1_ADDR,
                               REG_DAC1_VOLUME_IC_1_BYTE,
                               R1_DAC1_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_OP_STAGE_MUTES_IC_1_ADDR,
                               REG_OP_STAGE_MUTES_IC_1_BYTE,
                               R2_OP_STAGE_MUTES_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL0_IC_1_ADDR,
                               REG_PLL_CTRL0_IC_1_BYTE,
                               R3_PLL_CTRL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL1_IC_1_ADDR,
                               REG_PLL_CTRL1_IC_1_BYTE,
                               R4_PLL_CTRL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL2_IC_1_ADDR,
                               REG_PLL_CTRL2_IC_1_BYTE,
                               R5_PLL_CTRL2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL3_IC_1_ADDR,
                               REG_PLL_CTRL3_IC_1_BYTE,
                               R6_PLL_CTRL3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL4_IC_1_ADDR,
                               REG_PLL_CTRL4_IC_1_BYTE,
                               R7_PLL_CTRL4_IC_1_Default);
    // The code generated by SigmaStudio tool, but this register is a
    // read-only register, so comment them out.
    // SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PLL_CTRL5_IC_1_ADDR,
    //                            REG_PLL_CTRL5_IC_1_BYTE,
    //                            R8_PLL_CTRL5_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CLK_CONTROL_IC_1_ADDR,
                               REG_CLK_CONTROL_IC_1_BYTE,
                               R9_CLK_CONTROL_IC_1_Default);
    // SIGMA_WRITE_DELAY( chip_addr, R10_DELAY_IC_1_SIZE,
    // R10_DELAY_IC_1_Default );
    am_util_delay_ms(10);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CLKOUT_SEL_IC_1_ADDR,
                               REG_CLKOUT_SEL_IC_1_BYTE,
                               R11_CLKOUT_SEL_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_REGULATOR_IC_1_ADDR,
                               REG_REGULATOR_IC_1_BYTE,
                               R12_REGULATOR_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CORE_CONTROL_IC_1_ADDR,
                               REG_CORE_CONTROL_IC_1_BYTE,
                               R13_CORE_CONTROL_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SLEEP_INST_IC_1_ADDR,
                               REG_SLEEP_INST_IC_1_BYTE,
                               R14_SLEEP_INST_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CORE_ENABLE_IC_1_ADDR,
                               REG_CORE_ENABLE_IC_1_BYTE,
                               R15_CORE_ENABLE_IC_1_Default);

    // The code generated by SigmaStudio tool, but these three registers are
    // read-only registers, so comment them out.
    // SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DBREG0_IC_1_ADDR,
    //                            REG_DBREG0_IC_1_BYTE, R16_DBREG0_IC_1_Default);
    // SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DBREG1_IC_1_ADDR,
    //                            REG_DBREG1_IC_1_BYTE, R17_DBREG1_IC_1_Default);
    // SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DBREG2_IC_1_ADDR,
    //                            REG_DBREG2_IC_1_BYTE, R18_DBREG2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CORE_IN_MUX_0_1_IC_1_ADDR,
                               REG_CORE_IN_MUX_0_1_IC_1_BYTE,
                               R19_CORE_IN_MUX_0_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CORE_IN_MUX_2_3_IC_1_ADDR,
                               REG_CORE_IN_MUX_2_3_IC_1_BYTE,
                               R20_CORE_IN_MUX_2_3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_SOURCE_0_1_IC_1_ADDR,
                               REG_DAC_SOURCE_0_1_IC_1_BYTE,
                               R21_DAC_SOURCE_0_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PDM_SOURCE_0_1_IC_1_ADDR,
                               REG_PDM_SOURCE_0_1_IC_1_BYTE,
                               R22_PDM_SOURCE_0_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_SOURCE_0_1_IC_1_ADDR,
                               REG_SOUT_SOURCE_0_1_IC_1_BYTE,
                               R23_SOUT_SOURCE_0_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_SOURCE_2_3_IC_1_ADDR,
                               REG_SOUT_SOURCE_2_3_IC_1_BYTE,
                               R24_SOUT_SOURCE_2_3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_SOURCE_4_5_IC_1_ADDR,
                               REG_SOUT_SOURCE_4_5_IC_1_BYTE,
                               R25_SOUT_SOURCE_4_5_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_SOURCE_6_7_IC_1_ADDR,
                               REG_SOUT_SOURCE_6_7_IC_1_BYTE,
                               R26_SOUT_SOURCE_6_7_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC_SDATA_CH_IC_1_ADDR,
                               REG_ADC_SDATA_CH_IC_1_BYTE,
                               R27_ADC_SDATA_CH_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_0_1_IC_1_ADDR,
                               REG_ASRCO_SOURCE_0_1_IC_1_BYTE,
                               R28_ASRCO_SOURCE_0_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_2_3_IC_1_ADDR,
                               REG_ASRCO_SOURCE_2_3_IC_1_BYTE,
                               R29_ASRCO_SOURCE_2_3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRC_MODE_IC_1_ADDR,
                               REG_ASRC_MODE_IC_1_BYTE,
                               R30_ASRC_MODE_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC_CONTROL0_IC_1_ADDR,
                               REG_ADC_CONTROL0_IC_1_BYTE,
                               R31_ADC_CONTROL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC_CONTROL1_IC_1_ADDR,
                               REG_ADC_CONTROL1_IC_1_BYTE,
                               R32_ADC_CONTROL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC_CONTROL2_IC_1_ADDR,
                               REG_ADC_CONTROL2_IC_1_BYTE,
                               R33_ADC_CONTROL2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC_CONTROL3_IC_1_ADDR,
                               REG_ADC_CONTROL3_IC_1_BYTE,
                               R34_ADC_CONTROL3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC0_VOLUME_IC_1_ADDR,
                               REG_ADC0_VOLUME_IC_1_BYTE,
                               R35_ADC0_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC1_VOLUME_IC_1_ADDR,
                               REG_ADC1_VOLUME_IC_1_BYTE,
                               R36_ADC1_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC2_VOLUME_IC_1_ADDR,
                               REG_ADC2_VOLUME_IC_1_BYTE,
                               R37_ADC2_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ADC3_VOLUME_IC_1_ADDR,
                               REG_ADC3_VOLUME_IC_1_BYTE,
                               R38_ADC3_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_0_IC_1_ADDR,
                               REG_PGA_CONTROL_0_IC_1_BYTE,
                               R39_PGA_CONTROL_0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_1_IC_1_ADDR,
                               REG_PGA_CONTROL_1_IC_1_BYTE,
                               R40_PGA_CONTROL_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR,
                               REG_PGA_CONTROL_2_IC_1_BYTE,
                               R41_PGA_CONTROL_2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR,
                               REG_PGA_CONTROL_3_IC_1_BYTE,
                               R42_PGA_CONTROL_3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_STEP_CONTROL_IC_1_ADDR,
                               REG_PGA_STEP_CONTROL_IC_1_BYTE,
                               R43_PGA_STEP_CONTROL_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_10DB_BOOST_IC_1_ADDR,
                               REG_PGA_10DB_BOOST_IC_1_BYTE,
                               R44_PGA_10DB_BOOST_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_POP_SUPPRESS_IC_1_ADDR,
                               REG_POP_SUPPRESS_IC_1_BYTE,
                               R45_POP_SUPPRESS_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_TALKTHRU_IC_1_ADDR,
                               REG_TALKTHRU_IC_1_BYTE,
                               R46_TALKTHRU_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_TALKTHRU_GAIN0_IC_1_ADDR,
                               REG_TALKTHRU_GAIN0_IC_1_BYTE,
                               R47_TALKTHRU_GAIN0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_TALKTHRU_GAIN1_IC_1_ADDR,
                               REG_TALKTHRU_GAIN1_IC_1_BYTE,
                               R48_TALKTHRU_GAIN1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MIC_BIAS_IC_1_ADDR,
                               REG_MIC_BIAS_IC_1_BYTE,
                               R49_MIC_BIAS_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CONTROL1_IC_1_ADDR,
                               REG_DAC_CONTROL1_IC_1_BYTE,
                               R50_DAC_CONTROL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC0_VOLUME_IC_1_ADDR,
                               REG_DAC0_VOLUME_IC_1_BYTE,
                               R51_DAC0_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC1_VOLUME_IC_1_ADDR,
                               REG_DAC1_VOLUME_IC_1_BYTE,
                               R52_DAC1_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_OP_STAGE_MUTES_IC_1_ADDR,
                               REG_OP_STAGE_MUTES_IC_1_BYTE,
                               R53_OP_STAGE_MUTES_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SAI_0_IC_1_ADDR,
                               REG_SAI_0_IC_1_BYTE, R54_SAI_0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SAI_1_IC_1_ADDR,
                               REG_SAI_1_IC_1_BYTE, R55_SAI_1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_CONTROL0_IC_1_ADDR,
                               REG_SOUT_CONTROL0_IC_1_BYTE,
                               R56_SOUT_CONTROL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SOUT_CONTROL1_IC_1_ADDR,
                               REG_SOUT_CONTROL1_IC_1_BYTE,
                               R57_SOUT_CONTROL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PDM_OUT_IC_1_ADDR,
                               REG_PDM_OUT_IC_1_BYTE, R58_PDM_OUT_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PDM_PATTERN_IC_1_ADDR,
                               REG_PDM_PATTERN_IC_1_BYTE,
                               R59_PDM_PATTERN_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP0_IC_1_ADDR,
                               REG_MODE_MP0_IC_1_BYTE,
                               R60_MODE_MP0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP1_IC_1_ADDR,
                               REG_MODE_MP1_IC_1_BYTE,
                               R61_MODE_MP1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP2_IC_1_ADDR,
                               REG_MODE_MP2_IC_1_BYTE,
                               R62_MODE_MP2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP3_IC_1_ADDR,
                               REG_MODE_MP3_IC_1_BYTE,
                               R63_MODE_MP3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP4_IC_1_ADDR,
                               REG_MODE_MP4_IC_1_BYTE,
                               R64_MODE_MP4_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP5_IC_1_ADDR,
                               REG_MODE_MP5_IC_1_BYTE,
                               R65_MODE_MP5_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MODE_MP6_IC_1_ADDR,
                               REG_MODE_MP6_IC_1_BYTE,
                               R66_MODE_MP6_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PB_VOL_SET_IC_1_ADDR,
                               REG_PB_VOL_SET_IC_1_BYTE,
                               R67_PB_VOL_SET_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PB_VOL_CONV_IC_1_ADDR,
                               REG_PB_VOL_CONV_IC_1_BYTE,
                               R68_PB_VOL_CONV_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DEBOUNCE_MODE_IC_1_ADDR,
                               REG_DEBOUNCE_MODE_IC_1_BYTE,
                               R69_DEBOUNCE_MODE_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_RESERVED_IC_1_ADDR,
                               REG_RESERVED_IC_1_BYTE,
                               R70_RESERVED_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_OP_STAGE_CTRL_IC_1_ADDR,
                               REG_OP_STAGE_CTRL_IC_1_BYTE,
                               R71_OP_STAGE_CTRL_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DECIM_PWR_MODES_IC_1_ADDR,
                               REG_DECIM_PWR_MODES_IC_1_BYTE,
                               R72_DECIM_PWR_MODES_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_INTERP_PWR_MODES_IC_1_ADDR,
                               REG_INTERP_PWR_MODES_IC_1_BYTE,
                               R73_INTERP_PWR_MODES_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_BIAS_CONTROL0_IC_1_ADDR,
                               REG_BIAS_CONTROL0_IC_1_BYTE,
                               R74_BIAS_CONTROL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_BIAS_CONTROL1_IC_1_ADDR,
                               REG_BIAS_CONTROL1_IC_1_BYTE,
                               R75_BIAS_CONTROL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL0_IC_1_ADDR,
                               REG_PAD_CONTROL0_IC_1_BYTE,
                               R76_PAD_CONTROL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL1_IC_1_ADDR,
                               REG_PAD_CONTROL1_IC_1_BYTE,
                               R77_PAD_CONTROL1_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL2_IC_1_ADDR,
                               REG_PAD_CONTROL2_IC_1_BYTE,
                               R78_PAD_CONTROL2_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL3_IC_1_ADDR,
                               REG_PAD_CONTROL3_IC_1_BYTE,
                               R79_PAD_CONTROL3_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL4_IC_1_ADDR,
                               REG_PAD_CONTROL4_IC_1_BYTE,
                               R80_PAD_CONTROL4_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PAD_CONTROL5_IC_1_ADDR,
                               REG_PAD_CONTROL5_IC_1_BYTE,
                               R81_PAD_CONTROL5_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_FAST_RATE_IC_1_ADDR,
                               REG_FAST_RATE_IC_1_BYTE,
                               R82_FAST_RATE_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CONTROL0_IC_1_ADDR,
                               REG_DAC_CONTROL0_IC_1_BYTE,
                               R83_DAC_CONTROL0_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_VOL_BYPASS_IC_1_ADDR,
                               REG_VOL_BYPASS_IC_1_BYTE,
                               R84_VOL_BYPASS_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, PROGRAM_ADDR_IC_1, PROGRAM_SIZE_IC_1,
                               Program_Data_IC_1);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, BANK_A_PARAMETERS_ADDR_IC_1,
                               BANK_A_PARAMETERS_SIZE_IC_1,
                               BANK_A_PARAMETERS_IC_1);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_OP_STAGE_MUTES_IC_1_ADDR,
                               REG_OP_STAGE_MUTES_IC_1_BYTE,
                               R87_OP_STAGE_MUTES_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC0_VOLUME_IC_1_ADDR,
                               REG_DAC0_VOLUME_IC_1_BYTE,
                               R88_DAC0_VOLUME_IC_1_Default);
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC1_VOLUME_IC_1_ADDR,
                               REG_DAC1_VOLUME_IC_1_BYTE,
                               R89_DAC1_VOLUME_IC_1_Default);

    return status;
}

// ****************************************************************************
//
//  Deinitialize IOM I2C
//
// ****************************************************************************
uint32_t am_devices_adau1777_i2c_deinit(uint32_t ui32Module)
{
    if (ui32Module > AM_REG_IOM_NUM_MODULES)
    {
        return AM_DEVICES_ADAU1777_STATUS_OUT_OF_RANGE;
    }

    am_bsp_iom_pins_disable(ui32Module, AM_HAL_IOM_I2C_MODE);

    if (g_adau1777_IOMHandle != NULL)
    {
        //
        // Disable the IOM.
        //
        if (am_hal_iom_disable(g_adau1777_IOMHandle) )
        {
            return AM_DEVICES_ADAU1777_STATUS_INVALID_HANDLE;
        }

        //
        // Disable power to and uninitialize the IOM instance.
        //
        if (am_hal_iom_power_ctrl(g_adau1777_IOMHandle, AM_HAL_SYSCTRL_DEEPSLEEP, false) )
        {
            return AM_DEVICES_ADAU1777_STATUS_HW_ERR;
        }

        if (am_hal_iom_uninitialize(g_adau1777_IOMHandle) )
        {
            return AM_DEVICES_ADAU1777_STATUS_FAIL;
        }

        g_adau1777_IOMHandle = NULL;
    }

    return AM_DEVICES_ADAU1777_STATUS_SUCCESS;
}

uint32_t am_devices_adau1777_set_sample_rate(uint8_t chip_addr, uint32_t sample_rate)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE r50_ser_portfs_ic_1 = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_SAI_0_IC_1_ADDR, (uint32_t *)&r50_ser_portfs_ic_1, REG_SAI_0_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    r50_ser_portfs_ic_1 &= ~R50_SER_PORT_FS_IC_1_MASK;
    switch (sample_rate)
    {
        case 48000:
            r50_ser_portfs_ic_1 |= (0 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 8000:
            r50_ser_portfs_ic_1 |= (1 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 12000:
            r50_ser_portfs_ic_1 |= (2 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 16000:
            r50_ser_portfs_ic_1 |= (3 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 24000:
            r50_ser_portfs_ic_1 |= (4 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 32000:
            r50_ser_portfs_ic_1 |= (5 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 96000:
            r50_ser_portfs_ic_1 |= (6 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        case 192000:
            r50_ser_portfs_ic_1 |= (7 << R50_SER_PORT_FS_IC_1_SHIFT);
            break;

        default:
            return AM_DEVICES_ADAU1777_STATUS_INVALID_ARG;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SAI_0_IC_1_ADDR, REG_SAI_0_IC_1_BYTE, &r50_ser_portfs_ic_1);
}

uint32_t am_devices_adau1777_set_bclk_rate(uint8_t chip_addr, uint32_t bclk_cycles)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE bclk_rate_ic_1 = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_SAI_1_IC_1_ADDR, (uint32_t *)&bclk_rate_ic_1, REG_SAI_1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    bclk_rate_ic_1 &= ~R51_BCLKRATE_IC_1_MASK;
    if (bclk_cycles == 32)
    {
        bclk_rate_ic_1 |= (0 << R51_BCLKRATE_IC_1_SHIFT);
    }
    else if (bclk_cycles == 16)
    {
        bclk_rate_ic_1 |= (1 << R51_BCLKRATE_IC_1_SHIFT);
    }
    else
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_ARG;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SAI_1_IC_1_ADDR, REG_SAI_1_IC_1_BYTE, &bclk_rate_ic_1);
}

uint32_t am_devices_adau1777_set_sai_ms(uint8_t chip_addr, ad1777_sai_ms_mode_t mode)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE sai_ms_ic_1 = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_SAI_1_IC_1_ADDR, (uint32_t *)&sai_ms_ic_1, REG_SAI_1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    sai_ms_ic_1 = (sai_ms_ic_1 & ~R51_SAI_MS_IC_1_MASK) | (mode << R51_SAI_MS_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SAI_1_IC_1_ADDR, REG_SAI_1_IC_1_BYTE, &sai_ms_ic_1);
}

uint32_t am_devices_adau1777_mute_dac_0(uint8_t chip_addr, ad1777_dac_mute_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE dac_0_mute = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_DAC_CONTROL1_IC_1_ADDR, (uint32_t *)&dac_0_mute, REG_DAC_CONTROL1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // DAC0 is left channel
    dac_0_mute = (dac_0_mute & ~R46_DAC0_MUTE_IC_1_MASK) | (value << R46_DAC0_MUTE_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CONTROL1_IC_1_ADDR, REG_DAC_CONTROL1_IC_1_BYTE, &dac_0_mute);
}

uint32_t am_devices_adau1777_mute_dac_1(uint8_t chip_addr, ad1777_dac_mute_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE dac_1_mute = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_DAC_CONTROL1_IC_1_ADDR, (uint32_t *)&dac_1_mute, REG_DAC_CONTROL1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // DAC1 is right channel
    dac_1_mute = (dac_1_mute & ~R46_DAC1_MUTE_IC_1_MASK) | (value << R46_DAC1_MUTE_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CONTROL1_IC_1_ADDR, REG_DAC_CONTROL1_IC_1_BYTE, &dac_1_mute);
}

uint32_t am_devices_adau1777_set_dac_0_volume(uint8_t chip_addr, uint8_t vol)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE dac_0_vol = 0;
    state = am_devices_adau1777_i2c_read(chip_addr, REG_DAC0_VOLUME_IC_1_ADDR, (uint32_t *)&dac_0_vol, REG_DAC0_VOLUME_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // DAC0 volume, is left channel
    dac_0_vol = (dac_0_vol & ~R47_DAC_0_VOL_IC_1_MASK) | (vol << R47_DAC_0_VOL_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC0_VOLUME_IC_1_ADDR, REG_DAC0_VOLUME_IC_1_BYTE, &dac_0_vol);
}

uint32_t am_devices_adau1777_set_dac_1_volume(uint8_t chip_addr, uint8_t vol)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE dac_1_vol = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_DAC1_VOLUME_IC_1_ADDR, (uint32_t *)&dac_1_vol, REG_DAC1_VOLUME_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // DAC1 volume, is right channel
    dac_1_vol = (dac_1_vol & ~R48_DAC_1_VOL_IC_1_MASK) | (vol << R48_DAC_1_VOL_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC1_VOLUME_IC_1_ADDR, REG_DAC1_VOLUME_IC_1_BYTE, &dac_1_vol);
}

uint32_t am_devices_adau1777_set_asrco_source_0(uint8_t chip_addr, ad1777_asrc_out_source_t source)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE asrc_out_source = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_ASRCO_SOURCE_0_1_IC_1_ADDR, (uint32_t *)&asrc_out_source, REG_ASRCO_SOURCE_0_1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    asrc_out_source = (asrc_out_source & ~R24_ASRC_OUT_SOURCE0_IC_1_MASK) | (source << R24_ASRC_OUT_SOURCE0_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_0_1_IC_1_ADDR, REG_ASRCO_SOURCE_0_1_IC_1_BYTE, &asrc_out_source);
}

uint32_t am_devices_adau1777_set_asrco_source_1(uint8_t chip_addr, ad1777_asrc_out_source_t source)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE asrc_out_source = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_ASRCO_SOURCE_0_1_IC_1_ADDR, (uint32_t *)&asrc_out_source, REG_ASRCO_SOURCE_0_1_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    asrc_out_source = (asrc_out_source & ~R24_ASRC_OUT_SOURCE1_IC_1_MASK) | (source << R24_ASRC_OUT_SOURCE1_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_0_1_IC_1_ADDR, REG_ASRCO_SOURCE_0_1_IC_1_BYTE, &asrc_out_source);
}

uint32_t am_devices_adau1777_set_asrco_source_2(uint8_t chip_addr, ad1777_asrc_out_source_t source)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE asrc_out_source = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_ASRCO_SOURCE_2_3_IC_1_ADDR, (uint32_t *)&asrc_out_source, REG_ASRCO_SOURCE_2_3_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    asrc_out_source = (asrc_out_source & ~R25_ASRC_OUT_SOURCE2_IC_1_MASK) | (source << R25_ASRC_OUT_SOURCE2_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_2_3_IC_1_ADDR, REG_ASRCO_SOURCE_2_3_IC_1_BYTE, &asrc_out_source);
}

uint32_t am_devices_adau1777_set_asrco_source_3(uint8_t chip_addr, ad1777_asrc_out_source_t source)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE asrc_out_source = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_ASRCO_SOURCE_2_3_IC_1_ADDR, (uint32_t *)&asrc_out_source, REG_ASRCO_SOURCE_2_3_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    asrc_out_source = (asrc_out_source & ~R25_ASRC_OUT_SOURCE3_IC_1_MASK) | (source << R25_ASRC_OUT_SOURCE3_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_ASRCO_SOURCE_2_3_IC_1_ADDR, REG_ASRCO_SOURCE_2_3_IC_1_BYTE, &asrc_out_source);
}

uint32_t am_devices_adau1777_set_pga_mute_2(uint8_t chip_addr, ad1777_pga_mute_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_mute = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, (uint32_t *)&pga_mute, REG_PGA_CONTROL_2_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_mute = (pga_mute & ~R37_PGA_MUTE2_IC_1_MASK) | (value << R37_PGA_MUTE2_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, REG_PGA_CONTROL_2_IC_1_BYTE, &pga_mute);
}

uint32_t am_devices_adau1777_set_pga_mute_3(uint8_t chip_addr, ad1777_pga_mute_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_mute = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, (uint32_t *)&pga_mute, REG_PGA_CONTROL_3_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_mute = (pga_mute & ~R38_PGA_MUTE3_IC_1_MASK) | (value << R38_PGA_MUTE3_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, REG_PGA_CONTROL_3_IC_1_BYTE, &pga_mute);
}

uint32_t am_devices_adau1777_set_pga_en_2(uint8_t chip_addr, ad1777_pga_en_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_en = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, (uint32_t *)&pga_en, REG_PGA_CONTROL_2_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_en = (pga_en & ~R37_PGA_EN2_IC_1_MASK) | (value << R37_PGA_EN2_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, REG_PGA_CONTROL_2_IC_1_BYTE, &pga_en);
}

uint32_t am_devices_adau1777_set_pga_en_3(uint8_t chip_addr, ad1777_pga_en_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_en = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, (uint32_t *)&pga_en, REG_PGA_CONTROL_3_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_en = (pga_en & ~R38_PGA_EN3_IC_1_MASK) | (value << R38_PGA_EN3_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, REG_PGA_CONTROL_3_IC_1_BYTE, &pga_en);
}

uint32_t am_devices_adau1777_set_mic_bias_en_0(uint8_t chip_addr, ad1777_mic_bias_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE mic_en = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_MIC_BIAS_IC_1_ADDR, (uint32_t *)&mic_en, REG_MIC_BIAS_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    mic_en = (mic_en & ~R45_MIC_EN0_IC_1_MASK) | (value << R45_MIC_EN0_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MIC_BIAS_IC_1_ADDR, REG_MIC_BIAS_IC_1_BYTE, &mic_en);
}

uint32_t am_devices_adau1777_set_mic_bias_en_1(uint8_t chip_addr, ad1777_mic_bias_t value)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE mic_en = 0;

    state = am_devices_adau1777_i2c_read(chip_addr, REG_MIC_BIAS_IC_1_ADDR, (uint32_t *)&mic_en, REG_MIC_BIAS_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    mic_en = (mic_en & ~R45_MIC_EN1_IC_1_MASK) | (value << R45_MIC_EN1_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_MIC_BIAS_IC_1_ADDR, REG_MIC_BIAS_IC_1_BYTE, &mic_en);
}

uint32_t am_devices_adau1777_set_pga_gain_2(uint8_t chip_addr, uint16_t gain)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_gain = 0;

    // Validate gain parameter range: 0 to 0X3F (-12dB to 32.25dB)
    if (gain > 0x3F)
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_ARG;
    }

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, (uint32_t *)&pga_gain, REG_PGA_CONTROL_2_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_gain = (pga_gain & ~R37_PGA_GAIN2_IC_1_MASK) | (gain << R37_PGA_GAIN2_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_2_IC_1_ADDR, REG_PGA_CONTROL_2_IC_1_BYTE, &pga_gain);
}

uint32_t am_devices_adau1777_set_pga_gain_3(uint8_t chip_addr, uint16_t gain)
{
    uint32_t state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE pga_gain = 0;

    // Validate gain parameter range: 0 to 0X3F (-12dB to 32.25dB)
    if (gain > 0x3F)
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_ARG;
    }

    state = am_devices_adau1777_i2c_read(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, (uint32_t *)&pga_gain, REG_PGA_CONTROL_3_IC_1_BYTE);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    pga_gain = (pga_gain & ~R38_PGA_GAIN3_IC_1_MASK) | (gain << R38_PGA_GAIN3_IC_1_SHIFT);

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PGA_CONTROL_3_IC_1_ADDR, REG_PGA_CONTROL_3_IC_1_BYTE, &pga_gain);
}

uint32_t am_devices_adau1777_set_linear_gain(uint8_t chip_addr, uint8_t value)
{
    uint32_t     state = AM_DEVICES_ADAU1777_STATUS_SUCCESS;
    ADI_REG_TYPE control_data[4] = {0};

    // Validate gain parameter range: 0 to 15 (0dB to 15dB)
    if (value > 15)
    {
        return AM_DEVICES_ADAU1777_STATUS_INVALID_ARG;
    }

    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG0_STAGE0_B0_ADDR, 4, &linear_gain[value][0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // Enable PGA, activate gain trigger, configure soft switching
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG0_STAGE0_B1_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG0_STAGE0_B2_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG0_STAGE0_A2_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG1_STAGE0_B0_ADDR, 4, &linear_gain[value][0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    // Enable PGA, activate gain trigger, configure soft switching
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG1_STAGE0_B1_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG1_STAGE0_B2_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }
    state = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, MOD_GAIN1_ALG1_STAGE0_A2_ADDR, sizeof(control_data), &control_data[0]);
    if (state != AM_DEVICES_ADAU1777_STATUS_SUCCESS)
    {
        return state;
    }

    return state;
}
// ****************************************************************************
//
//  Deinitialize the adau1777 chip
//
// ****************************************************************************
uint32_t am_devices_adau1777_deinit(uint8_t chip_addr)
{
    // TODO
    return AM_DEVICES_ADAU1777_STATUS_SUCCESS;
}

//*****************************************************************************
//
// End Doxygen group.
//! @}
//
//*****************************************************************************
