//*****************************************************************************
//
//! @file am_devices_ssm6515.c
//!
//! @brief Analog Devices SSM6515 Digital Audio Amplifier Driver with I2C Interface.
//!
//! @addtogroup devices_ssm6515 SSM6515 I2C Audio Amplifier Driver
//! @ingroup devices
//! @{
//!
//! Purpose: This module provides a comprehensive hardware abstraction layer
//!          for the Analog Devices SSM6515 digital audio amplifier. The driver
//!          enables high-performance audio playback with extensive configuration
//!          options through I2C control interface. It supports wide sample rate
//!          ranges, multiple audio interface modes, power management, and gain
//!          control. Configuration tables are generated using Analog Devices'
//!          SigmaStudio tool for optimal audio performance and system integration.
//!
//! @section devices_ssm6515_features Key Features
//!
//! 1. @b High-Performance @b Audio @b Amplification: Digital Class-D amplifier with superior audio quality.
//! 2. @b Wide @b Sample @b Rate @b Support: 8kHz to 768kHz sample rates for diverse audio applications.
//! 3. @b Flexible @b Audio @b Interfaces: Stereo and TDM (Time Division Multiplexing) modes.
//! 4. @b TDM @b Slot @b Configuration: 16-bit, 24-bit, and 32-bit slot width support.
//! 5. @b Programmable @b Gain @b Control: Software-controlled volume adjustment.
//! 6. @b Power @b Management: Software power up/down control for energy efficiency.
//! 7. @b SigmaStudio @b Integration: Uses configuration tables generated by SigmaStudio tool.
//! 8. @b I2C @b Interface: Standard I2C communication for control and configuration.
//!
//! @section devices_ssm6515_functionality Functionality
//!
//! - Initialize and configure SSM6515 amplifier via I2C interface
//! - Configure wide range of audio sample rates (8kHz to 768kHz)
//! - Set audio interface mode (Stereo I2S or TDM)
//! - Configure TDM slot width for multi-channel audio systems
//! - Control amplifier gain for volume adjustment
//! - Manage power states for optimal energy consumption
//! - Load SigmaStudio-generated configuration tables
//! - Handle register-level configuration with read/write operations
//! - Support full reset and initialization sequences
//!
//! @section devices_ssm6515_usage Usage
//!
//! 1. Initialize I2C interface with am_devices_ssm6515_i2c_init()
//! 2. Initialize SSM6515 device with am_devices_ssm6515_init()
//! 3. Configure sample rate with am_devices_ssm6515_set_sample_rate()
//! 4. Set audio interface mode with am_devices_ssm6515_set_sai_mode()
//! 5. Configure TDM parameters with am_devices_ssm6515_set_tdm_slot_width()
//! 6. Adjust gain with am_devices_ssm6515_set_gain()
//! 7. Control power state with am_devices_ssm6515_power_down()
//! 8. Play audio through configured amplifier
//! 9. Deinitialize device with am_devices_ssm6515_deinit()
//! 10. Deinitialize I2C interface with am_devices_ssm6515_i2c_deinit()
//!
//! @section devices_ssm6515_configuration Configuration
//!
//! - Set up I2C interface parameters and timing
//! - Configure audio sample rates based on system requirements
//! - Set up audio interface mode (Stereo vs TDM) for system topology
//! - Configure TDM slot parameters for multi-channel audio
//! - Load SigmaStudio-generated configuration tables
//! - Set up gain control ranges and behavior
//! - Configure power management for optimal efficiency
//! - Optimize register settings for specific audio applications
//
//*****************************************************************************

//*****************************************************************************
//
// Copyright (c) 2026, Ambiq Micro, Inc.
// All rights reserved.
//
// This is part of revision stable-2026.06.18 of the AmbiqSuite Development Package.
//
//*****************************************************************************
#include "am_devices_ssm6515.h"
#include "am_bsp.h"
#include "string.h"
#include "am_util_delay.h"
#include "am_util_debug.h"
#include "am_util_stdio.h"

//*****************************************************************************
//
// Macro definitions.
//
//*****************************************************************************
#define MAX_TDM_SLOT_NUM 32

/*
    Default registers configuration table. Generated by SigmaStudio tool.
    Generation step:
    * Creat a SSM6515 project
    * Modify project parameters
        * Control/Status: Software Master PowerDown: Normal
        * Datapath
            * Sample Rate: 16KHz
            * Mute Control: DAC Unmuted
            * Power Mode: HP Amp Low Power Mode On.
    * Export System File. This function will output .h file.
*/

/* Register Default - IC 1.PWR_CTRL Register.PWR_CTRL */
ADI_REG_TYPE R0_PWR_CTRL_IC_1_PowerOn[REG_PWR_CTRL_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PWR_CTRL Register.PWR_CTRL */
ADI_REG_TYPE R0_PWR_CTRL_IC_1_PowerDown[REG_PWR_CTRL_IC_1_BYTE] = {
0x01
};


/* Register Default - IC 1.CLK_CTRL Register.CLK_CTRL */
ADI_REG_TYPE R1_CLK_CTRL_IC_1_Default[REG_CLK_CTRL_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.PDM_CTRL Register.PDM_CTRL */
ADI_REG_TYPE R2_PDM_CTRL_IC_1_Default[REG_PDM_CTRL_IC_1_BYTE] = {
0x20
};

/* Register Default - IC 1.DAC_CTRL1 Register.DAC_CTRL1 */
ADI_REG_TYPE R3_DAC_CTRL1_IC_1_Default[REG_DAC_CTRL1_IC_1_BYTE] = {
0x12 // change from 32KHz (0x14) to 16KHz sample rate
};

/* Register Default - IC 1.DAC_CTRL2 Register.DAC_CTRL2 */
ADI_REG_TYPE R4_DAC_CTRL2_IC_1_Default[REG_DAC_CTRL2_IC_1_BYTE] = {
0x02
};

/* Register Default - IC 1.DAC_CTRL3 Register.DAC_CTRL3 */
ADI_REG_TYPE R5_DAC_CTRL3_IC_1_Default[REG_DAC_CTRL3_IC_1_BYTE] = {
0xD0
};

/* Register Default - IC 1.DAC_VOL Register.DAC_VOL */
ADI_REG_TYPE R6_DAC_VOL_IC_1_Default[REG_DAC_VOL_IC_1_BYTE] = {
0x40
};

/* Register Default - IC 1.DAC_CLIP Register.DAC_CLIP */
ADI_REG_TYPE R7_DAC_CLIP_IC_1_Default[REG_DAC_CLIP_IC_1_BYTE] = {
0xFF
};

/* Register Default - IC 1.SPT_CTRL1 Register.SPT_CTRL1 */
ADI_REG_TYPE R8_SPT_CTRL1_IC_1_Default[REG_SPT_CTRL1_IC_1_BYTE] = {
0x11 // change format from I2S to TDM and TDM slot width 16 bits instead of 32 bits
};

/* Register Default - IC 1.SPT_CTRL2 Register.SPT_CTRL2 */
ADI_REG_TYPE R9_SPT_CTRL2_IC_1_Default[REG_SPT_CTRL2_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.AMP_CTRL Register.AMP_CTRL */
ADI_REG_TYPE R10_AMP_CTRL_IC_1_Default[REG_AMP_CTRL_IC_1_BYTE] = {
0x15
};

/* Register Default - IC 1.LIM_CTRL Register.LIM_CTRL */
ADI_REG_TYPE R11_LIM_CTRL_IC_1_Default[REG_LIM_CTRL_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.LIM_CTRL2 Register.LIM_CTRL2 */
ADI_REG_TYPE R12_LIM_CTRL2_IC_1_Default[REG_LIM_CTRL2_IC_1_BYTE] = {
0x0A
};

/* Register Default - IC 1.FAULT_CTRL Register.FAULT_CTRL */
ADI_REG_TYPE R13_FAULT_CTRL_IC_1_Default[REG_FAULT_CTRL_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.STATUS_CLR Register.STATUS_CLR */
ADI_REG_TYPE R14_STATUS_CLR_IC_1_Default[REG_STATUS_CLR_IC_1_BYTE] = {
0x00
};

/* Register Default - IC 1.RESET Register.RESET */
ADI_REG_TYPE R15_RESET_IC_1_Default[REG_RESET_IC_1_BYTE] = {
0x00
};

//*****************************************************************************
//
// Static variables.
//
//*****************************************************************************
static void *g_ssm6515_IOMHandle = NULL;

//*****************************************************************************
//
// Local functions public.
//
//*****************************************************************************
// As SIGMA_WRITE_REGISTER_BLOCK is exported by SigmaStudio tool, so reserve it.
static uint32_t SIGMA_WRITE_REGISTER_BLOCK(uint8_t dev_addr, uint8_t reg,
                                           uint16_t data_len, ADI_REG_TYPE *data)
{
    return am_devices_ssm6515_i2c_write(dev_addr, reg, (uint32_t *)data, data_len);
}

uint32_t am_devices_ssm6515_i2c_read(uint32_t dev_addr, uint8_t reg_addr,
                                     uint32_t *p_buf, uint32_t size)
{
    am_hal_iom_transfer_t Transaction;

    Transaction.ui8Priority        = 1;
    Transaction.ui32InstrLen       = 1;
    Transaction.ui64Instr          = reg_addr;
    Transaction.eDirection         = AM_HAL_IOM_RX;
    Transaction.ui32NumBytes       = size;
    Transaction.pui32RxBuffer      = p_buf;
    Transaction.bContinue          = false;
    Transaction.ui8RepeatCount     = 0;
    Transaction.ui32PauseCondition = 0;
    Transaction.ui32StatusSetClr   = 0;

    Transaction.uPeerInfo.ui32I2CDevAddr = dev_addr;
    if (am_hal_iom_blocking_transfer(g_ssm6515_IOMHandle, &Transaction) !=
        AM_HAL_STATUS_SUCCESS)
    {
        return AM_DEVICES_SSM6515_STATUS_INVALID_OPERATION;
    }

    return AM_DEVICES_SSM6515_STATUS_SUCCESS;
}

uint32_t am_devices_ssm6515_i2c_write(uint32_t dev_addr, uint8_t reg_addr,
                                      uint32_t *p_buf, uint32_t size)
{
    am_hal_iom_transfer_t Transaction;

    Transaction.ui8Priority        = 1;
    Transaction.ui32InstrLen       = 1;
    Transaction.ui64Instr          = reg_addr;
    Transaction.eDirection         = AM_HAL_IOM_TX;
    Transaction.ui32NumBytes       = size;
    Transaction.pui32TxBuffer      = p_buf;
    Transaction.bContinue          = false;
    Transaction.ui8RepeatCount     = 0;
    Transaction.ui32PauseCondition = 0;
    Transaction.ui32StatusSetClr   = 0;

    Transaction.uPeerInfo.ui32I2CDevAddr = dev_addr;
    if (am_hal_iom_blocking_transfer(g_ssm6515_IOMHandle, &Transaction) !=
        AM_HAL_STATUS_SUCCESS)
    {
        return AM_DEVICES_SSM6515_STATUS_INVALID_OPERATION;
    }

    return AM_DEVICES_SSM6515_STATUS_SUCCESS;
}

// ****************************************************************************
//
//  Initialize IOM I2C and DMA
//
// ****************************************************************************
uint32_t am_devices_ssm6515_i2c_init(uint32_t             ui32Module,
                                     am_hal_iom_config_t *psIOMSettings)
{
    if (ui32Module > AM_REG_IOM_NUM_MODULES)
    {
        return AM_DEVICES_SSM6515_STATUS_OUT_OF_RANGE;
    }

    if (g_ssm6515_IOMHandle != NULL)
    {
        return AM_DEVICES_SSM6515_STATUS_IN_USE;
    }

    //
    // Configure the IOM pins.
    //
    am_bsp_iom_pins_enable(ui32Module, AM_HAL_IOM_I2C_MODE);

    //
    // Initialize the IOM instance.
    // Enable power to the IOM instance.
    // Configure the IOM for Serial operation during initialization.
    // Enable the IOM.
    // HAL Success return is 0
    //
    if (am_hal_iom_initialize(ui32Module, &g_ssm6515_IOMHandle) ||
        am_hal_iom_power_ctrl(g_ssm6515_IOMHandle, AM_HAL_SYSCTRL_WAKE,
                              false) ||
        am_hal_iom_configure(g_ssm6515_IOMHandle, psIOMSettings) ||
        am_hal_iom_enable(g_ssm6515_IOMHandle))
    {
        return AM_DEVICES_SSM6515_STATUS_HW_ERR;
    }

    return AM_DEVICES_SSM6515_STATUS_SUCCESS;
}

// ****************************************************************************
//
//  Initialize the ssm6515 chip
//
// ****************************************************************************
uint32_t am_devices_ssm6515_init(uint8_t chip_addr)
{
    uint32_t status = AM_DEVICES_SSM6515_STATUS_SUCCESS;

    // Need to full reset first if it's on already to avoid noise or pop sound.
    ADI_REG_TYPE R15_RESET_IC_1 = 1 << R20_SOFT_FULL_RESET_IC_1_SHIFT;
    status = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_RESET_IC_1_ADDR, REG_RESET_IC_1_BYTE, &R15_RESET_IC_1);
    if (status != AM_DEVICES_SSM6515_STATUS_SUCCESS)
    {
        return status;
    }

    // Power on
    status = SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PWR_CTRL_IC_1_ADDR, REG_PWR_CTRL_IC_1_BYTE, R0_PWR_CTRL_IC_1_PowerOn);
    if (status != AM_DEVICES_SSM6515_STATUS_SUCCESS)
    {
        return status;
    }

    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_CLK_CTRL_IC_1_ADDR, REG_CLK_CTRL_IC_1_BYTE, R1_CLK_CTRL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PDM_CTRL_IC_1_ADDR, REG_PDM_CTRL_IC_1_BYTE, R2_PDM_CTRL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CTRL1_IC_1_ADDR, REG_DAC_CTRL1_IC_1_BYTE, R3_DAC_CTRL1_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CTRL2_IC_1_ADDR, REG_DAC_CTRL2_IC_1_BYTE, R4_DAC_CTRL2_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CTRL3_IC_1_ADDR, REG_DAC_CTRL3_IC_1_BYTE, R5_DAC_CTRL3_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_VOL_IC_1_ADDR, REG_DAC_VOL_IC_1_BYTE, R6_DAC_VOL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CLIP_IC_1_ADDR, REG_DAC_CLIP_IC_1_BYTE, R7_DAC_CLIP_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SPT_CTRL1_IC_1_ADDR, REG_SPT_CTRL1_IC_1_BYTE, R8_SPT_CTRL1_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SPT_CTRL2_IC_1_ADDR, REG_SPT_CTRL2_IC_1_BYTE, R9_SPT_CTRL2_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_AMP_CTRL_IC_1_ADDR, REG_AMP_CTRL_IC_1_BYTE, R10_AMP_CTRL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_LIM_CTRL_IC_1_ADDR, REG_LIM_CTRL_IC_1_BYTE, R11_LIM_CTRL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_LIM_CTRL2_IC_1_ADDR, REG_LIM_CTRL2_IC_1_BYTE, R12_LIM_CTRL2_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_FAULT_CTRL_IC_1_ADDR, REG_FAULT_CTRL_IC_1_BYTE, R13_FAULT_CTRL_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_STATUS_CLR_IC_1_ADDR, REG_STATUS_CLR_IC_1_BYTE, R14_STATUS_CLR_IC_1_Default );
    SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_RESET_IC_1_ADDR, REG_RESET_IC_1_BYTE, R15_RESET_IC_1_Default );

    return status;
}

// ****************************************************************************
//
//  Deinitialize IOM I2C and DMA
//
// ****************************************************************************
uint32_t am_devices_ssm6515_i2c_deinit(uint32_t ui32Module)
{
    if (ui32Module > AM_REG_IOM_NUM_MODULES)
    {
        return AM_DEVICES_SSM6515_STATUS_OUT_OF_RANGE;
    }

    am_bsp_iom_pins_disable(ui32Module, AM_HAL_IOM_I2C_MODE);

    if (g_ssm6515_IOMHandle != NULL)
    {
        //
        // Disable the IOM.
        //
        if (am_hal_iom_disable(g_ssm6515_IOMHandle) )
        {
            return AM_DEVICES_SSM6515_STATUS_INVALID_HANDLE;
        }

        //
        // Disable power to and uninitialize the IOM instance.
        //
        if (am_hal_iom_power_ctrl(g_ssm6515_IOMHandle, AM_HAL_SYSCTRL_DEEPSLEEP, false) )
        {
            return AM_DEVICES_SSM6515_STATUS_HW_ERR;
        }

        if (am_hal_iom_uninitialize(g_ssm6515_IOMHandle) )
        {
            return AM_DEVICES_SSM6515_STATUS_FAIL;
        }

        g_ssm6515_IOMHandle = NULL;
    }

    return AM_DEVICES_SSM6515_STATUS_SUCCESS;
}

uint32_t am_devices_ssm6515_set_gain(uint8_t chip_addr, uint8_t *gain)
{
    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_VOL_IC_1_ADDR, REG_DAC_VOL_IC_1_BYTE, gain);
}

uint32_t am_devices_ssm6515_power_down(uint8_t chip_addr, bool state)
{
    ADI_REG_TYPE power = 0;

    if (state)
    {
        power = SSM6515_DOWN;
    }
    else
    {
        power = SSM6515_UP;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_PWR_CTRL_IC_1_ADDR, REG_PWR_CTRL_IC_1_BYTE, &power);
}

uint32_t am_devices_ssm6515_set_sai_mode(uint8_t chip_addr, uint32_t mode)
{
    ADI_REG_TYPE spt_ctrl1 = 0;
    am_devices_ssm6515_i2c_read(chip_addr, REG_SPT_CTRL1_IC_1_ADDR, (uint32_t *)&spt_ctrl1, REG_SPT_CTRL1_IC_1_BYTE);

    spt_ctrl1 &= ~R12_SPT_SAI_MODE_IC_1_MASK;
    if (mode == SSM6515_STEREO)
    {
        spt_ctrl1 |= (0 << R12_SPT_SAI_MODE_IC_1_SHIFT);
    }
    else if (mode == SSM6515_TDM)
    {
        spt_ctrl1 |= (1 << R12_SPT_SAI_MODE_IC_1_SHIFT);
    }
    else
    {
        return AM_DEVICES_SSM6515_STATUS_INVALID_ARG;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SPT_CTRL1_IC_1_ADDR, REG_SPT_CTRL1_IC_1_BYTE, &spt_ctrl1);
}

uint32_t am_devices_ssm6515_set_tdm_slot_width(uint8_t chip_addr, uint32_t slot_width)
{
    ADI_REG_TYPE spt_ctrl1 = 0;
    am_devices_ssm6515_i2c_read(chip_addr, REG_SPT_CTRL1_IC_1_ADDR, (uint32_t *)&spt_ctrl1, REG_SPT_CTRL1_IC_1_BYTE);

    spt_ctrl1 &= ~R12_SPT_SLOT_WIDTH_IC_1_MASK;
    if (slot_width == 32)
    {
        spt_ctrl1 |= (0 << R12_SPT_SLOT_WIDTH_IC_1_SHIFT);
    }
    else if (slot_width == 16)
    {
        spt_ctrl1 |= (1 << R12_SPT_SLOT_WIDTH_IC_1_SHIFT);
    }
    else if (slot_width == 24)
    {
        spt_ctrl1 |= (2 << R12_SPT_SLOT_WIDTH_IC_1_SHIFT);
    }
    else
    {
        return AM_DEVICES_SSM6515_STATUS_INVALID_ARG;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SPT_CTRL1_IC_1_ADDR, REG_SPT_CTRL1_IC_1_BYTE, &spt_ctrl1);
}

uint32_t am_devices_ssm6515_set_sample_rate(uint8_t chip_addr, uint32_t sample_rate)
{
    ADI_REG_TYPE dac_ctrl1 = 0;
    am_devices_ssm6515_i2c_read(chip_addr, REG_DAC_CTRL1_IC_1_ADDR, (uint32_t *)&dac_ctrl1, REG_DAC_CTRL1_IC_1_BYTE);

    dac_ctrl1 &= ~R7_DAC_FS_IC_1_MASK;
    switch (sample_rate)
    {
        case 8000:
            dac_ctrl1 |= (0 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 12000:
            dac_ctrl1 |= (1 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 16000:
            dac_ctrl1 |= (2 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 24000:
            dac_ctrl1 |= (3 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 32000:
            dac_ctrl1 |= (4 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 44100:
        case 48000:
            dac_ctrl1 |= (5 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 88200:
        case 96000:
            dac_ctrl1 |= (6 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 174000:
        case 192000:
            dac_ctrl1 |= (7 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 384000:
            dac_ctrl1 |= (8 << R7_DAC_FS_IC_1_SHIFT);
            break;

        case 768000:
            dac_ctrl1 |= (9 << R7_DAC_FS_IC_1_SHIFT);
            break;

        default:
            return AM_DEVICES_SSM6515_STATUS_INVALID_ARG;
    }

    return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_DAC_CTRL1_IC_1_ADDR, REG_DAC_CTRL1_IC_1_BYTE, &dac_ctrl1);
}

uint32_t am_devices_ssm6515_select_tdm_slot(uint8_t chip_addr, uint32_t slot)
{
    ADI_REG_TYPE spt_ctrl2 = slot;

    if (spt_ctrl2 < MAX_TDM_SLOT_NUM)
    {
        return SIGMA_WRITE_REGISTER_BLOCK(chip_addr, REG_SPT_CTRL2_IC_1_ADDR, REG_SPT_CTRL2_IC_1_BYTE, &spt_ctrl2);
    }
    else
    {
        return AM_DEVICES_SSM6515_STATUS_INVALID_ARG;
    }

}

// ****************************************************************************
//
//  Deinitialize the ssm6515 chip
//
// ****************************************************************************
uint32_t am_devices_ssm6515_deinit(uint8_t chip_addr)
{
    // TODO
    return AM_DEVICES_SSM6515_STATUS_SUCCESS;
}

//*****************************************************************************
//
// End Doxygen group.
//! @}
//
//*****************************************************************************
