#!/usr/bin/env python3
"""Cross-compile the nsx-npu translation units with arm-none-eabi-gcc.

nsx-npu is the only module whose C sources have no other automated build
coverage: the CMake contract tests configure with the host compiler and cannot
build ARM code, and the container link smoke builds only the staged Apollo
boards. This check compiles each nsx-npu TU for the atomiq110 target with the
module's own warning policy (`-Wall -Wextra -Werror`) so a change that breaks
the build, or trips a warning in NSX-owned code, fails in CI rather than on the
FPGA.

Two levels of coverage:

* Always: `src/atomiq110/nsx_npu_timebase.c` against a generated stub of the
  two `nsx_ethos_u.h` hook prototypes it implements. The stub mirrors the
  contract in nsx-ethos-u-driver's `includes-api/nsx_ethos_u.h`.
* With `--ethos-u-driver-root` (or `NSX_ETHOS_U_DRIVER_ROOT`): every TU,
  including `src/nsx_npu.c`, against the real driver headers. The driver is
  registry-resolved by neuralspotx and is not part of this repository, so this
  level is opt-in.

Toolchain discovery: `--gcc`, then `$GCC_ROOT/bin/arm-none-eabi-gcc` (the
dev/CI container convention), then `arm-none-eabi-gcc` on PATH.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SOC = "atomiq110"
MODULE = "nsx-npu"

# Warning policy for NSX-owned sources. `-Wno-error=cpp` keeps the vendor HAL's
# `#warning` markers (FPGA build notes) from failing the compile; they are still
# printed. Vendor headers are included with -isystem so their own warnings do
# not count against the NSX TU.
WARNING_FLAGS = ("-Wall", "-Wextra", "-Werror", "-Wno-error=cpp")

STUB_HEADER = """\
/* Generated by tools/nsx_npu_compile_check.py.
 *
 * Minimal stand-in for nsx-ethos-u-driver's includes-api/nsx_ethos_u.h: only
 * the two weak timebase hooks that nsx_npu_timebase.c provides strong
 * overrides for. Their signatures must match the driver contract exactly.
 */
#ifndef NSX_ETHOS_U_H
#define NSX_ETHOS_U_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
uint64_t nsx_ethos_u_ticks(void);
uint32_t nsx_ethos_u_ticks_per_ms(void);
#ifdef __cplusplus
}
#endif
#endif
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def find_gcc(explicit: Path | None) -> Path | None:
    if explicit is not None:
        return explicit if explicit.is_file() else None
    gcc_root = os.environ.get("GCC_ROOT")
    if gcc_root:
        candidate = Path(gcc_root) / "bin" / "arm-none-eabi-gcc"
        if candidate.is_file():
            return candidate
    found = shutil.which("arm-none-eabi-gcc")
    return Path(found) if found else None


def read_soc_facts(repo: Path) -> dict[str, str | list[str]]:
    """Pull the compiler-facing facts out of cmake/socs/facts/<soc>.cmake.

    The facts file is the single source of truth for the SoC's CPU, float ABI
    and compile definitions; parsing it (rather than restating the values here)
    keeps this check honest when they change.
    """
    text = (repo / "cmake" / "socs" / "facts" / f"{SOC}.cmake").read_text(encoding="utf-8")

    def scalar(name: str) -> str:
        match = re.search(rf'^set\({name}\s+"([^"]*)"\)', text, re.MULTILINE)
        if match is None:
            raise ValueError(f"{name} not found in {SOC} facts")
        return match.group(1)

    defs_match = re.search(r"^set\(NSX_SOC_COMPILE_DEFINITIONS\s*\n(.*?)^\)", text, re.MULTILINE | re.DOTALL)
    if defs_match is None:
        raise ValueError(f"NSX_SOC_COMPILE_DEFINITIONS not found in {SOC} facts")
    definitions = [line.strip() for line in defs_match.group(1).splitlines() if line.strip() and not line.strip().startswith("#")]

    return {
        "cpu": scalar("NSX_CPU"),
        "float_abi": scalar("NSX_FLOAT_ABI"),
        "fpu": scalar("NSX_FPU"),
        "definitions": definitions,
    }


def compile_flags(repo: Path, facts: dict[str, str | list[str]]) -> list[str]:
    sdk = repo / "modules" / "nsx-ambiqsuite" / "sdk"
    mcu = sdk / "mcu" / SOC
    flags = [
        f"-mcpu={facts['cpu']}",
        "-mthumb",
        f"-mfloat-abi={facts['float_abi']}",
        "-std=c11",
        "-O2",
        *WARNING_FLAGS,
    ]
    if facts["fpu"]:
        flags.append(f"-mfpu={facts['fpu']}")
    flags += [f"-D{definition}" for definition in facts["definitions"]]
    # nsx-ambiq-hal's PUBLIC definition, and what the atomiq110 board's flags
    # target injects for its only realization.
    flags += ["-DNSX_AMBIQSUITE", "-Datomiq110_fpga_turbo", "-DNSX_BOARD_IS_FPGA=1"]
    for system_include in (
        repo / "modules" / "nsx-cmsis-core" / "Include",
        sdk / "CMSIS" / "AmbiqMicro" / "Include",
        mcu,
        mcu / "hal",
        mcu / "hal" / "mcu",
        sdk / "utils",
    ):
        flags += ["-isystem", str(system_include)]
    for include in (
        repo / "modules" / "nsx-core" / "includes-api",
        repo / "modules" / MODULE / "includes-api",
        repo / "modules" / MODULE / "src",
    ):
        flags += ["-I", str(include)]
    return flags


def module_sources(repo: Path) -> list[Path]:
    module = repo / "modules" / MODULE
    return [module / "src" / "nsx_npu.c", module / "src" / SOC / "nsx_npu_timebase.c"]


def run(command: list[str], *, verbose: bool) -> subprocess.CompletedProcess[str]:
    if verbose:
        print("+ " + " ".join(command), flush=True)
    return subprocess.run(command, text=True, capture_output=True, check=False)


def compile_one(gcc: Path, flags: list[str], extra_includes: list[Path], source: Path, output: Path, *, verbose: bool) -> bool:
    command = [str(gcc), "-c", *flags]
    for include in extra_includes:
        command += ["-I", str(include)]
    command += [str(source), "-o", str(output)]
    result = run(command, verbose=verbose)
    # Vendor `#warning` lines are expected noise; surface everything else.
    noise = re.compile(r"warning: #warning|^\s*\d+ \||^\s*\||^In file included from|^\s+from ")
    for line in result.stderr.splitlines():
        if not noise.search(line):
            print(line, file=sys.stderr)
    if result.returncode != 0:
        print(f"FAIL {source.relative_to(repo_root())}", flush=True)
        return False
    print(f"ok   {source.relative_to(repo_root())}", flush=True)
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo-root", type=Path, default=repo_root(), help="Path to nsx-ambiq-sdk checkout.")
    parser.add_argument("--gcc", type=Path, help="arm-none-eabi-gcc to use. Default: $GCC_ROOT/bin, then PATH.")
    parser.add_argument(
        "--ethos-u-driver-root",
        type=Path,
        default=Path(os.environ["NSX_ETHOS_U_DRIVER_ROOT"]) if os.environ.get("NSX_ETHOS_U_DRIVER_ROOT") else None,
        help="nsx-ethos-u-driver checkout. Enables compiling every nsx-npu TU against the real driver headers.",
    )
    parser.add_argument("--build-root", type=Path, default=Path("build/npu-compile-check"), help="Object/stub output root.")
    parser.add_argument("--verbose", action="store_true", help="Print each compiler command.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo = args.repo_root.expanduser().resolve()
    build_root = args.build_root.expanduser().resolve()

    gcc = find_gcc(args.gcc)
    if gcc is None:
        print("arm-none-eabi-gcc not found (tried --gcc, $GCC_ROOT/bin, PATH).", file=sys.stderr)
        return 2

    facts = read_soc_facts(repo)
    flags = compile_flags(repo, facts)
    sources = module_sources(repo)
    for source in sources:
        if not source.is_file():
            raise FileNotFoundError(source)

    build_root.mkdir(parents=True, exist_ok=True)
    ok = True

    stub_dir = build_root / "stub"
    stub_dir.mkdir(exist_ok=True)
    (stub_dir / "nsx_ethos_u.h").write_text(STUB_HEADER, encoding="utf-8")
    timebase = [source for source in sources if source.name == "nsx_npu_timebase.c"]
    print(f"[stub driver header] {gcc}")
    for source in timebase:
        ok &= compile_one(gcc, flags, [stub_dir], source, build_root / f"{source.stem}.stub.o", verbose=args.verbose)

    driver_root = args.ethos_u_driver_root
    if driver_root is not None:
        driver_root = driver_root.expanduser().resolve()
        driver_includes = [
            driver_root / "includes-api",
            driver_root / "external" / "ethos-u-core-driver" / "include",
        ]
        for include in driver_includes:
            if not include.is_dir():
                raise FileNotFoundError(include)
        print(f"[real driver headers] {driver_root}")
        for source in sources:
            ok &= compile_one(gcc, flags, driver_includes, source, build_root / f"{source.stem}.o", verbose=args.verbose)
    else:
        print("[real driver headers] skipped: pass --ethos-u-driver-root or set NSX_ETHOS_U_DRIVER_ROOT to compile nsx_npu.c too")

    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
